### ISSUE TITLE
[Insight] Sensitive data should not be present in non-parameter configuration files

### ISSUE THREAD

**Issue by pborreli** [pborreli/composer-service#10]
**[in app/config/security.yml, line 13](https://github.com/pborreli/composer-service/blob/master/app/config/security.yml#L13)**

> A sensitive data has been detected in your configuration file (`password` parameter). You should consider storing it in a single parameter file.

```

    providers:
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
```
